name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
      uses: biolab/orange-ci-cd/.github/workflows/test-addons.yml@master
  test-xgboost:
    # On MacOS libomp is required to run XGBoost
    name: "Test with XGBOOST"
    runs-on: macos-latest
    continue-on-error: false
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox

      - name: Install system dependencies on MacOS for xgboost
        run: brew install libomp

      - name: Test with Tox
        run: |
          tox -e orange-released
        env:
          QT_QPA_PLATFORM: offscreen
